declare module 'umy-ui'
declare module '*.js'
declare module 'lodash/cloneDeep'
declare module 'lodash/merge'
declare module 'lodash/isEqualWith'
declare module 'lodash/trim'
declare module 'calm-harbin'
