#!/usr/bin/env groovy

// 工作目录在 $WORKSPACE

node {
    nodejs('node') {
        // def a
        // stage('jenkins环境变量') {
        //     // a = $(sh "git rev-parse --short HEAD")
        //     // a= sh(script: "git rev-parse --short HEAD", returnStdout:true).trim()
        //     a= $(sh "git rev-parse --short HEAD")
        //     println a
        // }
        stage('拉取代码') {
            git branch: "${branch}", // 分支
                credentialsId: 'github', // 凭证
                url: 'https://github.com/CalmHarbin/calm-harbin.git' //仓库
        }
        stage('构建') {
            sh 'pwd'
            sh 'ls'
            
            if ("$install" == 'true') {
                sh 'rm -rf node_modules && yarn'
            }
            // 打包
            sh 'npm run docs:build'
            // 制作压缩包
            sh 'cd docs && tar -czf dist.tar.gz ./dist'
        }
        stage('部署') {
            sshPublisher(
                publishers: [
                    sshPublisherDesc(
                        configName: '阿里云', // 远程服务器名称，提前配置在jenkins中配置
                        transfers: [
                            sshTransfer(
                                cleanRemote: false, 
                                excludes: '', 
                                // 执行脚本
                                execCommand: 'cd /usr/share/nginx/html/ && rm -rf dist && tar -xzvf dist.tar.gz && rm -rf dist.tar.gz', 
                                execTimeout: 120000, 
                                flatten: false, 
                                makeEmptyDirs: false, 
                                noDefaultExcludes: false, 
                                patternSeparator: '[, ]+', 
                                // 复制到远程服务器的目录位置
                                remoteDirectory: '/usr/share/nginx/html/', 
                                remoteDirectorySDF: false, 
                                // 去除的前缀
                                removePrefix: 'docs/', 
                                // 需要复制的文件，位于jenkins的工作空间中
                                sourceFiles: 'docs/dist.tar.gz'
                            )
                        ], 
                        usePromotionTimestamp: false, 
                        useWorkspaceInPromotion: false, 
                        verbose: false
                    )
                ]
            )
            // 将容器内的文件copy到宿主机
            // sh 'docker cp myjenkins:/var/jenkins_mount/workspace/calmharbin文档/docs/dist /usr/share/nginx/html/dist'
            // 生成镜像
            // sh 'docker build -f /var/jenkins_mount/workspace/calmharbin文档/docs/Dockerfile -t calmharbin .'
            // 创建容器
            // sh 'docker run --name calmharbin -d -p 8888:80 -v'
        }
        stage('清理') {
            sh 'rm -rf docs/dist docs/dist.tar.gz'
        }
    }
}



